name: core
version: '0.1.2-alpha.4'
main: org.moniti.core.Core
api-version: '1.21'
authors: [ Beans-mc devs ]
description: The main Beans-mc server core plugin.
website: https://github.com/beansmc/core
commands:
  core:
    description: The main command for the core plugin.
  radio:
    description: A configurable in-game radio that plays random discs when wanted.
