name: core
version: '0.2.6-alpha.5'
main: org.moniti.core.Core
api-version: '1.21'
authors: [ Beans-mc devs ]
description: The main Beans-mc server core plugin.
website: https://github.com/beansmc/core
commands:
  core:
    description: The main command for the core plugin.
  flyspeed:
    description: Sets the player's current fly speed (1-10).
    permission: core.command.flyspeed
  msg:
    description: Privately message another player.
    aliases: [tell, w]
